force-app/main/default/objects/Account/fields/Accept_Email_Marketing__c.field-meta.xml
<CustomField>
    <fullName>Accept_Email_Marketing__c</fullName>
    <label>Accept Email Marketing</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Addres__c.field-meta.xml
<CustomField>
    <fullName>Addres__c</fullName>
    <label>Street</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Countrytext__c.field-meta.xml
<CustomField>
    <fullName>Countrytext__c</fullName>
    <label>Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Districttext__c.field-meta.xml
<CustomField>
    <fullName>Districttext__c</fullName>
    <label>District</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/External__c.field-meta.xml
<CustomField>
    <fullName>External__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Provincetext__c.field-meta.xml
<CustomField>
    <fullName>Provincetext__c</fullName>
    <label>Province</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Total_Orders__c.field-meta.xml
<CustomField>
    <fullName>Total_Orders__c</fullName>
    <label>Total Orders.</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Total_Spent__c.field-meta.xml
<CustomField>
    <fullName>Total_Spent__c</fullName>
    <label>Total Spent.</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Wardtext__c.field-meta.xml
<CustomField>
    <fullName>Wardtext__c</fullName>
    <label>Ward</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Addresses__c/Customer_Addresses__c.object-meta.xml
<CustomObject>
    <label>Customer Addresses</label>
    <nameField>
        <displayFormat>CAN-{000000}</displayFormat>
        <label>Customer Adresses Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Addresses__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Addresses</relationshipLabel>
    <relationshipName>Customer_Addresses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Customer_Addresses__c/fields/Address_1__c.field-meta.xml
<CustomField>
    <fullName>Address_1__c</fullName>
    <label>Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Addresses__c/fields/Country1__c.field-meta.xml
<CustomField>
    <fullName>Country1__c</fullName>
    <label>Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Addresses__c/fields/District_text__c.field-meta.xml
<CustomField>
    <fullName>District_text__c</fullName>
    <label>District</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Addresses__c/fields/Province_text__c.field-meta.xml
<CustomField>
    <fullName>Province_text__c</fullName>
    <label>Province</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Addresses__c/fields/Ward_text__c.field-meta.xml
<CustomField>
    <fullName>Ward_text__c</fullName>
    <label>Ward</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/WebhookAPIUpdateCustomer.cls
@RestResource(urlMapping = '/HaravanWebhook/APIUpdateCustomer/*')
global without sharing class WebhookAPIUpdateCustomer{
    @HttpPost
    global static void WebhookAPIUpdateCustomer(){
        RestRequest req = RestContext.request;
        String jsonResponse = req.requestBody.toString();
        Map<String, Object> responseMap = (Map<String, Object>)JSON.deserializeUntyped(jsonResponse);
        String ExternalId = String.valueOf((Decimal) responseMap.get('id'));
        Object default_address = (Object) responseMap.get('default_address');
        Map<String, Object> MapDefaultAddress = (Map<String, Object>)default_address;
        List<Object> lstAddresses = (List<Object>)responseMap.get('addresses');
        Map<String, Object> mapAddress = (Map<String, Object>)lstAddresses[0];
        String recordTypeId = [SELECT Id, Name
                               From RecordType
                               Where Name = 'Person Account'].Id;
        List<Account> lstAcc = [SELECT Id
                                FROM Account
                                Where External__c = :ExternalId];
        if (lstAcc.size() > 0){
            Account acc = lstAcc.get(0);
            acc.External__c = ExternalId;
            acc.LastName = (String) responseMap.get('last_name');
            acc.FirstName = (String) responseMap.get('first_name');
            acc.RecordTypeId = recordTypeId;
            acc.Phone = (String) MapDefaultAddress.get('phone');
            acc.PersonMobilePhone = String.valueOf((String) responseMap.get('phone'));
            acc.PersonEmail = (String) responseMap.get('email');
            acc.PersonBirthdate = Date.valueOf((String) responseMap.get('birthday'));
            acc.Total_Spent__c = (Decimal) responseMap.get('total_spent');
            acc.Total_Orders__c = (Decimal) responseMap.get('orders_count');
            acc.Addres__c = (String) MapDefaultAddress.get('address1');
            acc.Notes__c = (String) responseMap.get('note');
            acc.Gender__c = String.valueOf((Decimal) responseMap.get('gender'));
            acc.Wardtext__c = (String) MapDefaultAddress.get('ward');
            acc.Districttext__c = (String) MapDefaultAddress.get('district');
            acc.Provincetext__c = (String) MapDefaultAddress.get('province');
            acc.Countrytext__c = (String) MapDefaultAddress.get('country');
            acc.Accept_Email_Marketing__c = String.valueOf((Boolean) responseMap.get('accepts_marketing'));
            update acc;
            List<Customer_Addresses__c> lstCusAddress = new List<Customer_Addresses__c>();
            for (Integer i = 0; i < lstAddresses.size(); i++){
                Customer_Addresses__c cusAddress = new Customer_Addresses__c();
                Map<String, Object> mapAdd = (Map<String, Object>)lstAddresses[i];
                cusAddress.Address_1__c = (String) mapAdd.get('address1');
                cusAddress.External_Id__c = String.valueOf((Decimal) mapAdd.get('id'));
                cusAddress.Account__c = acc.Id;
                cusAddress.Province_text__c = (String) mapAdd.get('province');
                cusAddress.District_text__c = (String) mapAdd.get('district');
                cusAddress.Ward_text__c = (String) mapAdd.get('ward');
                cusAddress.Country1__c = (String) mapAdd.get('country');
                lstCusAddress.add(cusAddress);
            }
            if (lstCusAddress.size() > 0){
                upsert lstCusAddress External_Id__c;
            }
        }
    }

}