force-app/main/default/objects/Account/fields/Customer_Level__c.field-meta.xml
<CustomField>
    <fullName>Customer_Level__c</fullName>
    <label>Customer Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>⭐</fullName>
                <default>true</default>
                <label>⭐</label>
            </value>
            <value>
                <fullName>⭐⭐</fullName>
            </value>
            <value>
                <fullName>⭐⭐⭐</fullName>
            </value>
            <value>
                <fullName>⭐⭐⭐⭐</fullName>
            </value>
            <value>
                <fullName>⭐⭐⭐⭐⭐</fullName>
            </value>
            <value>
                <fullName>1</fullName>
                <isActive>false</isActive>
                <label>1</label>
            </value>
            <value>
                <fullName>2</fullName>
                <isActive>false</isActive>
                <label>2</label>
            </value>
            <value>
                <fullName>3</fullName>
                <isActive>false</isActive>
                <label>3</label>
            </value>
            <value>
                <fullName>4</fullName>
                <isActive>false</isActive>
                <label>4</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Districttext__c.field-meta.xml
<CustomField>
    <fullName>Districttext__c</fullName>
    <label>District</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Ordered__c.field-meta.xml
<CustomField>
    <fullName>Ordered__c</fullName>
    <label>Ordered</label>
    <summaryForeignKey>Haravan_Order__c.Customer__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/fields/Provincetext__c.field-meta.xml
<CustomField>
    <fullName>Provincetext__c</fullName>
    <label>Province</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Total_Orders_Rollup__c.field-meta.xml
<CustomField>
    <fullName>Total_Orders_Rollup__c</fullName>
    <label>Total Orders</label>
    <summaryForeignKey>Haravan_Order__c.Customer__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/fields/Total_Spent_Rollup__c.field-meta.xml
<CustomField>
    <fullName>Total_Spent_Rollup__c</fullName>
    <label>Total Spent</label>
    <summarizedField>Haravan_Order__c.TOTAL_PAYMENT_INCLUDE_SHIP__c</summarizedField>
    <summaryForeignKey>Haravan_Order__c.Customer__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/fields/Wardtext__c.field-meta.xml
<CustomField>
    <fullName>Wardtext__c</fullName>
    <label>Ward</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billing_Address__c/Billing_Address__c.object-meta.xml
<CustomObject>
    <label>Billing Address</label>
    <nameField>
        <label>Billing Address Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Billing_Address__c/fields/Haravan_Order__c.field-meta.xml
<CustomField>
    <fullName>Haravan_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Haravan Order</label>
    <referenceTo>Haravan_Order__c</referenceTo>
    <relationshipName>Billing_Address</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Haravan_Order__c/Haravan_Order__c.object-meta.xml
<CustomObject>
    <label>Retail orders</label>
    <nameField>
        <displayFormat>#{000000}</displayFormat>
        <label>Haravan Order Code</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Haravan_Order__c/fields/CLV__c.field-meta.xml
<CustomField>
    <fullName>CLV__c</fullName>
    <formula>Customer__r.Total_Spent_Rollup__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lifetime Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Haravan_Order__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Haravan_Order</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Haravan_Order__c/fields/Order_date__c.field-meta.xml
<CustomField>
    <fullName>Order_date__c</fullName>
    <label>Order date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Haravan_Order__c/fields/Ordered__c.field-meta.xml
<CustomField>
    <fullName>Ordered__c</fullName>
    <label>Ordered</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Haravan_Order__c/fields/Sales_Channel__c.field-meta.xml
<CustomField>
    <fullName>Sales_Channel__c</fullName>
    <label>Sales Channel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Web</fullName>
            </value>
            <value>
                <fullName>POS</fullName>
            </value>
            <value>
                <fullName>fb</fullName>
                <label>Facebook</label>
            </value>
            <value>
                <fullName>haravan_draft_order</fullName>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Zalo</fullName>
            </value>
            <value>
                <fullName>Phone</fullName>
            </value>
            <value>
                <fullName>Staff</fullName>
            </value>
            <value>
                <fullName>Lazada</fullName>
            </value>
            <value>
                <fullName>Tiki</fullName>
            </value>
            <value>
                <fullName>fbshop</fullName>
                <label>Facebook Shop</label>
            </value>
            <value>
                <fullName>Harafunnel</fullName>
            </value>
            <value>
                <fullName>app_android</fullName>
                <label>App Android</label>
            </value>
            <value>
                <fullName>app_ios</fullName>
                <label>App IOS</label>
            </value>
            <value>
                <fullName>HaraPOS</fullName>
            </value>
            <value>
                <fullName>Shopee</fullName>
            </value>
            <value>
                <fullName>googleshop</fullName>
                <label>Google Shop</label>
            </value>
            <value>
                <fullName>Harasocial</fullName>
            </value>
            <value>
                <fullName>Sendo</fullName>
            </value>
            <value>
                <fullName>tiktokshop</fullName>
                <label>Tiktok Shop</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Haravan_Order__c/fields/Total_Payment__c.field-meta.xml
<CustomField>
    <fullName>Total_Payment__c</fullName>
    <label>Total Payment(notuse)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Haravan_Order__c/fields/TOTAL_PAYMENT_INCLUDE_SHIP__c.field-meta.xml
<CustomField>
    <fullName>TOTAL_PAYMENT_INCLUDE_SHIP__c</fullName>
    <formula>Total_Payment_For__c   +  Shipping__c -  Discount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Haravan_Order_item__c/Haravan_Order_item__c.object-meta.xml
<CustomObject>
    <label>Order Item</label>
    <nameField>
        <displayFormat>OI-{00000000}</displayFormat>
        <label>Order Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Haravan_Order_item__c/fields/Haravan_Order__c.field-meta.xml
<CustomField>
    <fullName>Haravan_Order__c</fullName>
    <label>Haravan Order</label>
    <referenceTo>Haravan_Order__c</referenceTo>
    <relationshipLabel>Order Item</relationshipLabel>
    <relationshipName>Haravan_Order_and_Product_Variant</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Haravan_Order_item__c/fields/product__c.field-meta.xml
<CustomField>
    <fullName>product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>HaravanProductVariant__c</referenceTo>
    <relationshipName>Haravan_Order_and_Product_Variant</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Haravan_Order_item__c/fields/Total_Payment__c.field-meta.xml
<CustomField>
    <fullName>Total_Payment__c</fullName>
    <formula>(Price__c  *  Quantity__c)  -   Total_Discount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Payment</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Haravan_Product__c/Haravan_Product__c.object-meta.xml
<CustomObject>
    <label>Retail Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HaravanProductVariant__c/HaravanProductVariant__c.object-meta.xml
<CustomObject>
    <label>Product Variants</label>
    <nameField>
        <label>Variant Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HaravanProductVariant__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <referenceTo>Haravan_Product__c</referenceTo>
    <relationshipLabel>Product Variants</relationshipLabel>
    <relationshipName>Haravan_Product_Variant</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order/fields/Billing_Address__c.field-meta.xml
<CustomField>
    <fullName>Billing_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Address</label>
    <referenceTo>Billing_Address__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CustomerOrderInfoController.cls
public with sharing class CustomerOrderInfoController{
    @AuraEnabled
    public static List<Haravan_Order__c> getOrderInfo(String OrderId){
        try{
            return [SELECT Id, Name, Customer__c, Customer__r.Name, Ordered__c, Customer__r.Total_Spent_Rollup__c, Customer__r.Total_Orders_Rollup__c, Customer__r.PersonBirthdate, CLV__c, Customer__r.PersonMobilePhone, Customer__r.PersonEmail, Customer__r.Notes__c, Customer__r.PersonGenderIdentity
                    FROM Haravan_Order__c
                    WHERE ID = :OrderId
                    LIMIT 1];
        } catch (DmlException e){
            throw e;
        }
    }

    @AuraEnabled
    public static List<Billing_Address__c> getBillingAddressInfo(String OrderId){
        try{
            return [SELECT ID, Address_1__c, District_text__c, Ward_text__c, Province_text__c
                    FROM Billing_Address__c
                    WHERE Haravan_Order__c = :OrderId];
        } catch (DmlException e){
            throw e;
        }
    }

    @AuraEnabled
    public static List<Account> getAccountInfo(String AccountId){
        try{
            return [SELECT Id, Name, Customer_Level__c, Ordered__c, Total_Spent_Rollup__c, PersonBirthdate, PersonMobilePhone, PersonEmail, Default_Address__pr.Address_1__c, Districttext__c, Wardtext__c, Provincetext__c, Notes__c, PersonGenderIdentity
                    from Account
                    Where Id = :AccountId];
        } catch (DmlException e){
            throw e;
        }
    }

    @AuraEnabled
    public static List<AggregateResult> getChartofProductFamily(String AccountId){
        System.debug('12345:' + AccountId);
        try{
            List<Haravan_Order__c> listIdOrder = [SELECT Id
                                                  From Haravan_Order__c
                                                  where Customer__c = :AccountId];
            System.debug('12345:' + listIdOrder);
            String strSelect = 'SELECT SUM(Total_Payment__c), product__r.product__r.Name ';
            String strFrom = 'FROM Haravan_Order_item__c ';
            String strWhere = '';
            if (listIdOrder.size() > 0){
                strWhere += ' WHERE Haravan_Order__c IN : listIdOrder ';
            }
            String strGroupby = 'GROUP BY product__r.product__r.Name';
            String query = strSelect + strFrom + strWhere + strGroupby;
            List<AggregateResult> lstResult = new List<AggregateResult>();
            lstResult = Database.query(query);
            System.debug('12345:' + query);
            System.debug('12345:' + lstResult);
            return lstResult;
        } catch (DmlException e){
            throw e;
        }
    }

    @AuraEnabled
    public static List<AggregateResult> getChartofRevenue6Month(String AccountId){
        try{
            List<Integer> lstMonth = new List<Integer>{ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 };
            Integer intMonth = Date.today().month() + 1;
            Integer intYear = Date.today().year();
            Set<Integer> lst6Month = new Set<Integer>();
            Set<Integer> lstYear = new Set<Integer>();
            if (intMonth < 6){
                lstYear.add(intYear);
                lstYear.add(intYear - 1);
            } else{
                lstYear.add(intYear);
            }
            for (Integer i = 6; i > 0; i--){
                System.debug('12345:' + (intMonth - i));
                lst6Month.add(intMonth - i);
            }
            List<AggregateResult> lstRevenue6Month = [SELECT SUM(TOTAL_PAYMENT_INCLUDE_SHIP__c), CALENDAR_MONTH(Order_date__c), CALENDAR_YEAR(Order_date__c)
                                                      from Haravan_Order__c
                                                      WHERE CALENDAR_MONTH(Order_date__c) IN:lst6Month AND CALENDAR_YEAR(Order_date__c) IN:lstYear AND Customer__c = :AccountId
                                                      group by CALENDAR_MONTH(Order_date__c), CALENDAR_YEAR(Order_date__c)
                                                      ORDER BY CALENDAR_YEAR(Order_date__c)];
            return lstRevenue6Month;
        } catch (Exception e){
            throw e;
        }
    }

    @AuraEnabled
    public static Map<String,AggregateResult> getCharofSalesChannels(String AccountId){
        try{
            List<AggregateResult> lstSalesChannels = [SELECT SUM(TOTAL_PAYMENT_INCLUDE_SHIP__c), Sales_Channel__c
                                                      FROM Haravan_Order__c
                                                      WHERE Customer__c = :AccountId
                                                      GROUP BY Sales_Channel__c
                                                      ORDER BY SUM(TOTAL_PAYMENT_INCLUDE_SHIP__c) DESC];
            List<String> pickListValuesList = new List<String>();
            Schema.DescribeFieldResult fieldResult = Haravan_Order__c.Sales_Channel__c.getDescribe();
            List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
            for (Schema.PicklistEntry pickListVal : ple){
                pickListValuesList.add(pickListVal.getLabel());
            }
            // Map<String, List<AggregateResult>> map = new Map<String, List<AggregateResult>>();
            Map<string, Aggregateresult> m = new Map<String, Aggregateresult>();
            System.debug('1234:' + lstSalesChannels);
            System.debug('12345:' + lstSalesChannels[0].get('Sales_Channel__c'));
            for (Integer i = 0; i < lstSalesChannels.size(); i++){
                for (Integer j = 0; j < ple.size(); j++){
                    if (lstSalesChannels[i].get('Sales_Channel__c') == ple[j].getValue()){
                        m.put(ple[j].getLabel(), lstSalesChannels[i]);
                    }
                }
            }
            System.debug('12345:' + m);

            return m;
        } catch (Exception e){
            throw e;
        }
    }

}