force-app/main/default/objects/Account/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>District</label>
    <referenceTo>District__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/External__c.field-meta.xml
<CustomField>
    <fullName>External__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Province__c.field-meta.xml
<CustomField>
    <fullName>Province__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Province/City</label>
    <referenceTo>Province__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Ward__c.field-meta.xml
<CustomField>
    <fullName>Ward__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ward/Commune</label>
    <referenceTo>Ward__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billing_Address__c/Billing_Address__c.object-meta.xml
<CustomObject>
    <label>Billing Address</label>
    <nameField>
        <label>Billing Address Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Billing_Address__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>District</label>
    <referenceTo>District__c</referenceTo>
    <relationshipName>Billing_Address</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billing_Address__c/fields/Haravan_Order__c.field-meta.xml
<CustomField>
    <fullName>Haravan_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Haravan Order</label>
    <referenceTo>Haravan_Order__c</referenceTo>
    <relationshipName>Billing_Address</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billing_Address__c/fields/Province__c.field-meta.xml
<CustomField>
    <fullName>Province__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Province</label>
    <referenceTo>Province__c</referenceTo>
    <relationshipName>Billing_Address</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billing_Address__c/fields/Ward__c.field-meta.xml
<CustomField>
    <fullName>Ward__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ward</label>
    <referenceTo>Ward__c</referenceTo>
    <relationshipName>Billing_Address</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/District__c/District__c.object-meta.xml
<CustomObject>
    <label>District</label>
    <nameField>
        <label>District Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/District__c/fields/Province__c.field-meta.xml
<CustomField>
    <fullName>Province__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Province</label>
    <referenceTo>Province__c</referenceTo>
    <relationshipLabel>District</relationshipLabel>
    <relationshipName>District</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Haravan_Order__c/Haravan_Order__c.object-meta.xml
<CustomObject>
    <label>Retail orders</label>
    <nameField>
        <displayFormat>#{000000}</displayFormat>
        <label>Haravan Order Code</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Haravan_Order__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Haravan_Order</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Haravan_Order__c/fields/Customer_Note__c.field-meta.xml
<CustomField>
    <fullName>Customer_Note__c</fullName>
    <label>Customer Note</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Haravan_Order__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <label>Discount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Haravan_Order__c/fields/Fulfillment_Status__c.field-meta.xml
<CustomField>
    <fullName>Fulfillment_Status__c</fullName>
    <label>Fulfillment Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Waiting for deliver</fullName>
            </value>
            <value>
                <fullName>fulfilled</fullName>
                <label>Fulfilled</label>
            </value>
            <value>
                <fullName>cancelled</fullName>
                <label>Canceled</label>
            </value>
            <value>
                <fullName>notfulfilled</fullName>
                <label>Notfulfilled</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>success</fullName>
                <label>Success</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Haravan_Order__c/fields/Order_Processing_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Processing_Status__c</fullName>
    <label>Order Processing Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>self_delivery</fullName>
                <label>Self Delivery</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Haravan_Order__c/fields/Payment_method__c.field-meta.xml
<CustomField>
    <fullName>Payment_method__c</fullName>
    <label>Payment method</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Haravan_Order__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Haravan_Order__c/fields/Sales_Channel__c.field-meta.xml
<CustomField>
    <fullName>Sales_Channel__c</fullName>
    <label>Sales Channel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Web</fullName>
            </value>
            <value>
                <fullName>POS</fullName>
            </value>
            <value>
                <fullName>fb</fullName>
                <label>Facebook</label>
            </value>
            <value>
                <fullName>haravan_draft_order</fullName>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Zalo</fullName>
            </value>
            <value>
                <fullName>Phone</fullName>
            </value>
            <value>
                <fullName>Staff</fullName>
            </value>
            <value>
                <fullName>Lazada</fullName>
            </value>
            <value>
                <fullName>Tiki</fullName>
            </value>
            <value>
                <fullName>fbshop</fullName>
                <label>Facebook Shop</label>
            </value>
            <value>
                <fullName>Harafunnel</fullName>
            </value>
            <value>
                <fullName>app_android</fullName>
                <label>App Android</label>
            </value>
            <value>
                <fullName>app_ios</fullName>
                <label>App IOS</label>
            </value>
            <value>
                <fullName>HaraPOS</fullName>
            </value>
            <value>
                <fullName>Shopee</fullName>
            </value>
            <value>
                <fullName>googleshop</fullName>
                <label>Google Shop</label>
            </value>
            <value>
                <fullName>Harasocial</fullName>
            </value>
            <value>
                <fullName>Sendo</fullName>
            </value>
            <value>
                <fullName>tiktokshop</fullName>
                <label>Tiktok Shop</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Haravan_Order__c/fields/Shipping__c.field-meta.xml
<CustomField>
    <fullName>Shipping__c</fullName>
    <label>Shipping</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Haravan_Order__c/fields/Total_Payment__c.field-meta.xml
<CustomField>
    <fullName>Total_Payment__c</fullName>
    <label>Total Payment(notuse)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Haravan_Order_item__c/Haravan_Order_item__c.object-meta.xml
<CustomObject>
    <label>Order Item</label>
    <nameField>
        <displayFormat>OI-{00000000}</displayFormat>
        <label>Order Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Haravan_Order_item__c/fields/Haravan_Order__c.field-meta.xml
<CustomField>
    <fullName>Haravan_Order__c</fullName>
    <label>Haravan Order</label>
    <referenceTo>Haravan_Order__c</referenceTo>
    <relationshipLabel>Order Item</relationshipLabel>
    <relationshipName>Haravan_Order_and_Product_Variant</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Haravan_Order_item__c/fields/Total_Payment__c.field-meta.xml
<CustomField>
    <fullName>Total_Payment__c</fullName>
    <formula>(Price__c  *  Quantity__c)  -   Total_Discount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Payment</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Chờ xử lý</fullName>
            </value>
            <value>
                <fullName>Thanh toán một phần</fullName>
            </value>
            <value>
                <fullName>Đã thanh toán</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shipping_Address__c/Shipping_Address__c.object-meta.xml
<CustomObject>
    <label>Shipping Address</label>
    <nameField>
        <displayFormat>SD-{000000}</displayFormat>
        <label>Shipping Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipping_Address__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <label>District</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Shipping_Address__c/fields/Haravan_Order__c.field-meta.xml
<CustomField>
    <fullName>Haravan_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Haravan Order</label>
    <referenceTo>Haravan_Order__c</referenceTo>
    <relationshipLabel>Shipping Address</relationshipLabel>
    <relationshipName>Shipping_Address</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipping_Address__c/fields/Province__c.field-meta.xml
<CustomField>
    <fullName>Province__c</fullName>
    <label>Province</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Shipping_Address__c/fields/Ward__c.field-meta.xml
<CustomField>
    <fullName>Ward__c</fullName>
    <label>Ward</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/WebhookAPICreateOrder.cls
@RestResource(urlMapping = '/HaravanWebhook/APICreateOrder/*')
global without sharing class WebhookAPICreateOrder{
    @HttpPost
    global static void WebhookAPICreateOrder(){
        RestRequest req = RestContext.request;
        String jsonResponse = req.requestBody.toString();
        Map<String, Object> responseMap = (Map<String, Object>)JSON.deserializeUntyped(jsonResponse);
        Object customer = (Object) responseMap.get('customer');
        Map<String, Object> mapCustomer = (Map<String, Object>)customer;
        List<Object> lstShippingLines = (List<Object>)responseMap.get('shipping_lines');
        Map<String, Object> mapShippingLines = (Map<String, Object>)lstShippingLines[0];
        Object shipping_address = (Object) responseMap.get('shipping_address');
        Object billing_address = (Object) responseMap.get('billing_address');
        Map<String, Object> mapShippingAddress = (Map<String, Object>)shipping_address;
        Map<String, Object> mapBillingAddress = (Map<String, Object>)billing_address;
        List<String> ExternalIdVariant = new List<String>();
        Map<String, Id> mapIdVariant = new Map<String, Id>();
        List<Haravan_Order_item__c> lstOrderItem = new List<Haravan_Order_item__c>();
        List<Object> lstLineItems = (List<Object>)responseMap.get('line_items');
        // Map<String, Object> mapLineItems = (Map<String, Objetc>) lstLineItems

        Haravan_Order__c order = new Haravan_Order__c();

        String ExIdCustomer = String.valueOf((Decimal) mapCustomer.get('id'));
        List<Account> acc = [SELECT Id, PersonContactId
                       From Account
                       Where External__c = :ExIdCustomer];
        if (acc.size() > 0){
            try{
                order.External_Id__c = String.valueOf((Decimal) responseMap.get('id'));
                order.Customer__c = acc[0].Id;
                order.Email__c = (String) mapCustomer.get('email');
                order.Discount__c = (Decimal) responseMap.get('total_discounts');
                order.Shipping__c = (Decimal) mapShippingLines.get('price');
                order.Total_Payment__c = (Decimal) responseMap.get('total_price');
                order.Customer_Note__c = (String) mapCustomer.get('note');
                order.Notes__c = (String) responseMap.get('note');
                order.Payment_method__c = (String) responseMap.get('gateway');
                order.Fulfillment_Status__c = (String) responseMap.get('fulfillment_status');
                order.Payment_Status__c = (String) responseMap.get('financial_status');
                order.Sales_Channel__c = (String) responseMap.get('source');
                order.Order_Processing_Status__c = (String) responseMap.get('order_processing_status');
                insert order;

                Shipping_Address__c shippingAddress = new Shipping_Address__c();
                // shippingAddress.External_Id__c = String.valueOf((Decimal) mapShippingAddress.get('id'));
                shippingAddress.Street__c = (String) mapShippingAddress.get('address1');
                shippingAddress.District__c = (String) mapShippingAddress.get('district');
                shippingAddress.Ward__c = (String) mapShippingAddress.get('ward');
                shippingAddress.Haravan_Order__c = order.Id;
                shippingAddress.Province__c = (String) mapShippingAddress.get('province');
                shippingAddress.Country__c = (String) mapShippingAddress.get('country');
                insert shippingAddress;

                Billing_Address__c billingAddress = new Billing_Address__c();
                billingAddress.External_Id__c = String.valueOf((Decimal) mapBillingAddress.get('id'));
                billingAddress.Name = order.Id;
                billingAddress.Address_1__c = (String) mapBillingAddress.get('address1');
                billingAddress.Contact__c = acc[0].PersonContactId;
                billingAddress.Phone__c = (String) mapBillingAddress.get('phone');
                billingAddress.Haravan_Order__c = order.Id;
                billingAddress.Province_text__c = (String) mapBillingAddress.get('province');
                billingAddress.District_text__c = (String) mapBillingAddress.get('district');
                billingAddress.Ward_text__c = (String) mapBillingAddress.get('ward');
                billingAddress.Countrytext__c = (String) mapBillingAddress.get('country');
                billingAddress.Company__c = (String) mapBillingAddress.get('company');
                upsert billingAddress External_Id__c;

                for (Integer i = 0; i < lstLineItems.size(); i++){
                    Map<String, Object> mapLineItems = (Map<String, Object>)lstLineItems[i];
                    ExternalIdVariant.add(String.valueOf((Decimal) mapLineItems.get('variant_id')));
                }
                System.debug('12345:' + ExternalIdVariant);

                List<HaravanProductVariant__c> lstVariant = [SELECT Id, External_Id__c
                                                             FROM HaravanProductVariant__c
                                                             Where External_Id__c IN:ExternalIdVariant];
                System.debug('12345:' + lstVariant);
                for (Integer i = 0; i < lstVariant.size(); i++){
                    for (Integer j = 0; j < ExternalIdVariant.size(); j++){
                        if (ExternalIdVariant[j] == lstVariant[i].External_Id__c){
                            mapIdVariant.put(ExternalIdVariant[j], lstVariant[i].Id);
                        }
                    }
                }
                for (Integer i = 0; i < lstLineItems.size(); i++){
                    Haravan_Order_item__c orderItem = new Haravan_Order_item__c();
                    Map<String, Object> mapLineItems = (Map<String, Object>)lstLineItems[i];
                    orderItem.Haravan_Order__c = order.Id;
                    orderItem.Quantity__c = (Decimal) mapLineItems.get('quantity');
                    orderItem.Price__c = (Decimal) mapLineItems.get('price_original');
                    orderItem.Total__c = (Decimal) mapLineItems.get('price');
                    orderItem.Discount__c = (Decimal) mapLineItems.get('total_discount');
                    for (Integer j = 0; j < mapIdVariant.size(); j++){
                        if (mapIdVariant.containsKey(String.valueOf((Decimal) mapLineItems.get('variant_id')))){
                            System.debug('12345:' + mapIdVariant.get(String.valueOf((Decimal) mapLineItems.get('variant_id'))));
                            orderItem.product__c = mapIdVariant.get(String.valueOf((Decimal) mapLineItems.get('variant_id')));
                        }
                    }
                    lstOrderItem.add(orderItem);
                }
                insert lstOrderItem;
            } catch (Exception e){
                System.debug('Error: ' + e.getMessage());
            }
        }
    }
}