force-app/main/default/objects/Account/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>District</label>
    <referenceTo>District__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/External__c.field-meta.xml
<CustomField>
    <fullName>External__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Province__c.field-meta.xml
<CustomField>
    <fullName>Province__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Province/City</label>
    <referenceTo>Province__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Ward__c.field-meta.xml
<CustomField>
    <fullName>Ward__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ward/Commune</label>
    <referenceTo>Ward__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/District__c/District__c.object-meta.xml
<CustomObject>
    <label>District</label>
    <nameField>
        <label>District Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/District__c/fields/Province__c.field-meta.xml
<CustomField>
    <fullName>Province__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Province</label>
    <referenceTo>Province__c</referenceTo>
    <relationshipLabel>District</relationshipLabel>
    <relationshipName>District</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Haravan_Order__c/Haravan_Order__c.object-meta.xml
<CustomObject>
    <label>Retail orders</label>
    <nameField>
        <displayFormat>#{000000}</displayFormat>
        <label>Haravan Order Code</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Haravan_Order__c/fields/Fulfillment_Status__c.field-meta.xml
<CustomField>
    <fullName>Fulfillment_Status__c</fullName>
    <label>Fulfillment Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Waiting for deliver</fullName>
            </value>
            <value>
                <fullName>fulfilled</fullName>
                <label>Fulfilled</label>
            </value>
            <value>
                <fullName>cancelled</fullName>
                <label>Canceled</label>
            </value>
            <value>
                <fullName>notfulfilled</fullName>
                <label>Notfulfilled</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>success</fullName>
                <label>Success</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Haravan_Order__c/fields/Haravan_shipment__c.field-meta.xml
<CustomField>
    <fullName>Haravan_shipment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Haravan shipment</label>
    <referenceTo>Haravan_shipment__c</referenceTo>
    <relationshipName>Haravan_Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Haravan_Order__c/fields/Order_Processing_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Processing_Status__c</fullName>
    <label>Order Processing Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>self_delivery</fullName>
                <label>Self Delivery</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Haravan_Order__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Haravan_shipment__c/Haravan_shipment__c.object-meta.xml
<CustomObject>
    <label>Retail Shipment</label>
    <nameField>
        <displayFormat>Shipment -{000000000}</displayFormat>
        <label>Shipment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Haravan_shipment__c/fields/Buyer__c.field-meta.xml
<CustomField>
    <fullName>Buyer__c</fullName>
    <label>Buyer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Haravan_shipment</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Haravan_shipment__c/fields/Carrier_COD_Status__c.field-meta.xml
<CustomField>
    <fullName>Carrier_COD_Status__c</fullName>
    <label>Carrier COD Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Chưa lấy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Haravan_shipment__c/fields/Carrier_Status__c.field-meta.xml
<CustomField>
    <fullName>Carrier_Status__c</fullName>
    <label>Carrier Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Chờ lấy hàng</fullName>
            </value>
            <value>
                <fullName>Hủy giao hàng</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Haravan_shipment__c/fields/COD_amount__c.field-meta.xml
<CustomField>
    <fullName>COD_amount__c</fullName>
    <label>COD amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Haravan_shipment__c/fields/Haravan_Order__c.field-meta.xml
<CustomField>
    <fullName>Haravan_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Id</label>
    <referenceTo>Haravan_Order__c</referenceTo>
    <relationshipName>Haravan_shipment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Haravan_shipment__c/fields/Note_for_shipment__c.field-meta.xml
<CustomField>
    <fullName>Note_for_shipment__c</fullName>
    <label>Note for shipment</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Haravan_shipment__c/fields/Status1__c.field-meta.xml
<CustomField>
    <fullName>Status1__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Haravan_shipment__c/fields/Total_weight__c.field-meta.xml
<CustomField>
    <fullName>Total_weight__c</fullName>
    <label>Total weight</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Haravan_shipment__c/fields/Tracking_number__c.field-meta.xml
<CustomField>
    <fullName>Tracking_number__c</fullName>
    <label>Tracking number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Chờ xử lý</fullName>
            </value>
            <value>
                <fullName>Thanh toán một phần</fullName>
            </value>
            <value>
                <fullName>Đã thanh toán</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Province__c/Province__c.object-meta.xml
<CustomObject>
    <label>Province</label>
    <nameField>
        <label>Province Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Province__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Province</relationshipLabel>
    <relationshipName>Province</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipping_Address__c/Shipping_Address__c.object-meta.xml
<CustomObject>
    <label>Shipping Address</label>
    <nameField>
        <displayFormat>SD-{000000}</displayFormat>
        <label>Shipping Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipping_Address__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <label>District</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Shipping_Address__c/fields/Haravan_Order__c.field-meta.xml
<CustomField>
    <fullName>Haravan_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Haravan Order</label>
    <referenceTo>Haravan_Order__c</referenceTo>
    <relationshipLabel>Shipping Address</relationshipLabel>
    <relationshipName>Shipping_Address</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipping_Address__c/fields/Province__c.field-meta.xml
<CustomField>
    <fullName>Province__c</fullName>
    <label>Province</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Shipping_Address__c/fields/Ward__c.field-meta.xml
<CustomField>
    <fullName>Ward__c</fullName>
    <label>Ward</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Ward__c/Ward__c.object-meta.xml
<CustomObject>
    <label>Ward</label>
    <nameField>
        <label>Ward Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/WebhookAPIUpdateOrder.cls
@RestResource(urlMapping = '/HaravanWebhook/APIUpdateOrder/*')
global without sharing class WebhookAPIUpdateOrder{
    @HttpPost
    global static void WebhookAPIUpdateOrder(){
        RestRequest req = RestContext.request;
        String jsonResponse = req.requestBody.toString();
        Map<String, Object> responseMap = (Map<String, Object>)JSON.deserializeUntyped(jsonResponse);
        String getCancelStatus = (String) responseMap.get('cancelled_status');
        Object customer = (Object) responseMap.get('customer');
        Map<String, Object> mapCustomer = (Map<String, Object>)customer;
        String ExIdCustomer = String.valueOf((Decimal) mapCustomer.get('id'));
        String ExIdOrder = String.valueOf((Decimal) responseMap.get('id'));
        Object shipping_address = (Object) responseMap.get('shipping_address');
        Object billing_address = (Object) responseMap.get('billing_address');
        Map<String, Object> mapShippingAddress = (Map<String, Object>)shipping_address;
        Map<String, Object> mapBillingAddress = (Map<String, Object>)billing_address;
        Haravan_shipment__c shipment = new Haravan_shipment__c();
        Account acc = [SELECT Id, PersonContactId
                       From Account
                       Where External__c = :ExIdCustomer];
        List<Haravan_Order__c> order = [SELECT Id, Order_Processing_Status__c
                                        From Haravan_Order__c
                                        WHERE External_Id__c = :ExIdOrder];
        Shipping_Address__c shippingAddress = [SELECT Id
                                               FROM Shipping_Address__c
                                               WHERE Haravan_Order__c = :order[0].Id];
        if (order.size() > 0){
            order[0].Notes__c = (String) responseMap.get('note');
            order[0].Payment_Status__c = (String) responseMap.get('financial_status');
            order[0].Order_Processing_Status__c = (String) responseMap.get('order_processing_status');
            if(getCancelStatus == 'cancelled'){
                order[0].Fulfillment_Status__c = getCancelStatus;
            }else {
                order[0].Fulfillment_Status__c = (String) responseMap.get('fulfillment_status');
            }
            update order;

            System.debug('12345:' + String.valueOf((Decimal) mapShippingAddress.get('id')));
            System.debug('12345:' + String.valueOf((Decimal) mapBillingAddress.get('id')));
            // Shipping_Address__c shippingAddress = new Shipping_Address__c();
            shippingAddress.External_Id__c = String.valueOf((Decimal) mapShippingAddress.get('id'));
            shippingAddress.Street__c = (String) mapShippingAddress.get('address1');
            shippingAddress.District__c = (String) mapShippingAddress.get('district');
            shippingAddress.Ward__c = (String) mapShippingAddress.get('ward');
            shippingAddress.Haravan_Order__c = order[0].Id;
            shippingAddress.Province__c = (String) mapShippingAddress.get('province');
            shippingAddress.Country__c = (String) mapShippingAddress.get('country');
            update shippingAddress;
        }
        try {
            List<Object> fulfillments = (List<Object>) responseMap.get('fulfillments');
            Map<String, Object> mapFulfillments = (Map<String, Object>) fulfillments[0];
            System.debug('12345 : ' + mapFulfillments);
            System.debug('12345 : ' + mapFulfillments.size());
            if(mapFulfillments.size() > 0){
                shipment.External_Id__c = String.valueOf((Decimal)mapFulfillments.get('id'));
                shipment.Buyer__c = acc.Id;
                shipment.Haravan_Order__c = order[0].Id;
                shipment.Tracking_number__c = String.valueOf((Decimal)mapFulfillments.get('tracking_number'));
                shipment.COD_amount__c = (Decimal)mapFulfillments.get('cod_amount');
                shipment.Size__c = String.valueOf((Decimal)mapFulfillments.get('package_length')) + ' x ' + String.valueOf((Decimal)mapFulfillments.get('package_width')) + ' x ' + String.valueOf((Decimal)mapFulfillments.get('package_height'));
                shipment.Total_weight__c = (Decimal)mapFulfillments.get('total_weight');
                shipment.Note_for_shipment__c = (String)mapFulfillments.get('shipping_notes');
                shipment.Status1__c = (String)mapFulfillments.get('status');
                shipment.Carrier_Status__c = (String)mapFulfillments.get('carrier_status_name');
                shipment.Carrier_COD_Status__c = (String)mapFulfillments.get('carrier_cod_status_name');
                upsert shipment External_Id__c;
            }
        } catch (Exception e) {
            
        }

    }

}