force-app/main/default/objects/Haravan_Product__c/Haravan_Product__c.object-meta.xml
<CustomObject>
    <label>Retail Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Haravan_Product__c/fields/Description1__c.field-meta.xml
<CustomField>
    <fullName>Description1__c</fullName>
    <label>Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Haravan_Product__c/fields/Images_Text__c.field-meta.xml
<CustomField>
    <fullName>Images_Text__c</fullName>
    <label>Images Text</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Haravan_Product__c/fields/promotionproducttext__c.field-meta.xml
<CustomField>
    <fullName>promotionproducttext__c</fullName>
    <label>Promotion Product</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Haravan_Product__c/fields/Type1__c.field-meta.xml
<CustomField>
    <fullName>Type1__c</fullName>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Haravan_Product__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <label>Vendor</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/HaravanProductVariant__c/HaravanProductVariant__c.object-meta.xml
<CustomObject>
    <label>Product Variants</label>
    <nameField>
        <label>Variant Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HaravanProductVariant__c/fields/CompareatPrice__c.field-meta.xml
<CustomField>
    <fullName>CompareatPrice__c</fullName>
    <inlineHelpText>Pre-discount Price</inlineHelpText>
    <label>Compare at Price</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/HaravanProductVariant__c/fields/ContinueSellingWhenOutofStock__c.field-meta.xml
<CustomField>
    <fullName>ContinueSellingWhenOutofStock__c</fullName>
    <label>Continue Selling When Out of Stock</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HaravanProductVariant__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <referenceTo>Haravan_Product__c</referenceTo>
    <relationshipLabel>Product Variants</relationshipLabel>
    <relationshipName>Haravan_Product_Variant</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HaravanProductVariant__c/fields/SKU__c.field-meta.xml
<CustomField>
    <fullName>SKU__c</fullName>
    <inlineHelpText>Stock Keeping Unit, should be unique and contain both characters and numbers</inlineHelpText>
    <label>SKU</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HaravanProductVariant__c/fields/Thisisaphysicalproduct__c.field-meta.xml
<CustomField>
    <fullName>Thisisaphysicalproduct__c</fullName>
    <label>This is a physical product</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HaravanProductVariant__c/fields/UnitPrice__c.field-meta.xml
<CustomField>
    <fullName>UnitPrice__c</fullName>
    <inlineHelpText>Selling Price</inlineHelpText>
    <label>Unit Price</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/WebhookAPIUpdateProduct.cls
@RestResource(urlMapping='/HaravanWebhook/APIUpdateProduct/*')
global without sharing class WebhookAPIUpdateProduct {
    @HttpPost
    global static void UpdateProduct() {
        RestRequest req =  RestContext.request;
        String jsonRespone = req.requestBody.toString();
        System.debug(jsonRespone);
        Map<String,Object> responseMap = (Map<String, Object>) JSON.deserializeUntyped(jsonRespone);
        String idProd  = String.valueOf((Integer) responseMap.get('id'));
        List<Haravan_Product__c> lstProd = [SELECT Id, Name, External_Id__c FROM Haravan_Product__c WHERE External_Id__c =: idProd];
        if (lstProd.size() >0 ) {
            try {
                Haravan_Product__c prod = lstProd.get(0);
                prod.External_Id__c = idProd;
                prod.Name = (String) responseMap.get('title');
                prod.Vendor__c = (String) responseMap.get('vendor');
                prod.Quote__c = (String) responseMap.get('body_plain');
                prod.Description1__c = (String) responseMap.get('body_html');
                prod.Type1__c = (String) responseMap.get('product_type');
                prod.Tags__c = (String) responseMap.get('tags');
                prod.promotionproducttext__c = String.valueOf((Boolean) responseMap.get('not_allow_promotion'));
                //prod.Images_Text__c = (String) responseMap.get('vendor');
                update prod;
                List<HaravanProductVariant__c> lstProdVar = new List<HaravanProductVariant__c>();
                List<Object> listVar = (List<Object>) responseMap.get('variants');
                for (Integer i=0; i<listVar.size(); i++) {
                    HaravanProductVariant__c prodVar = new HaravanProductVariant__c();
                    Map<String,Object> mapProdVar = (Map<String,Object>) listVar[i];
                    prodVar.Product__c = prod.Id;
                    prodVar.External_Id__c = String.valueOf((Integer) mapProdVar.get('id'));
                    prodVar.Name = (String) mapProdVar.get('title');
                    prodVar.UnitPrice__c = (Decimal) mapProdVar.get('price');
                    prodVar.SKU__c = (String) mapProdVar.get('sku');
                    prodVar.Barcode__c = (String) mapProdVar.get('barcode');
                    prodVar.Color__c = (String) mapProdVar.get('option2');
                    prodVar.Size__c = (String) mapProdVar.get('option3');
                    prodVar.Weight__c = (Decimal) mapProdVar.get('grams');
                    prodVar.CompareatPrice__c = (Decimal) mapProdVar.get('compare_at_price');
                    prodVar.Material__c = (String) mapProdVar.get('option3');
                    prodVar.Thisisaphysicalproduct__c = String.valueOf((Boolean) mapProdVar.get('requires_shipping'));
                    prodVar.ContinueSellingWhenOutofStock__c = (String) mapProdVar.get('inventory_policy');
                    lstProdVar.add(prodVar);
                }
                if (lstProdVar.size() >0) {
                    upsert lstProdVar External_Id__c;
                }
            } catch (Exception e) {
                System.debug('Error: '+e.getMessage());
            }
        } else {
            
        }
    }
}